"use client"

import { useState } from "react"
import {
  BET_COPY_FORMATS,
  BET_COPY_TEXT_STYLES,
  convertStandardBetText,
  type BetCopyFormatId,
  type BetCopyTextStyleId,
} from "@/lib/bet-copy-format"

interface BetFormatConverterProps {
  isOpen: boolean
  onClose: () => void
}

export default function BetFormatConverter({ isOpen, onClose }: BetFormatConverterProps) {
  const [input, setInput] = useState("")
  const [format, setFormat] = useState<BetCopyFormatId>("dash")
  const [textStyle, setTextStyle] = useState<BetCopyTextStyleId>("normal")
  const [output, setOutput] = useState("")
  const [betCount, setBetCount] = useState(0)
  const [error, setError] = useState("")
  const [copied, setCopied] = useState(false)

  if (!isOpen) return null

  const generate = () => {
    try {
      const result = convertStandardBetText(input, format, textStyle)
      setOutput(result.output)
      setBetCount(result.betCount)
      setError("")
      setCopied(false)
    } catch (conversionError) {
      setOutput("")
      setBetCount(0)
      setError(conversionError instanceof Error ? conversionError.message : "Unable to format these bets.")
    }
  }

  const copyOutput = async () => {
    if (!output) return
    await navigator.clipboard.writeText(output)
    setCopied(true)
    window.setTimeout(() => setCopied(false), 1800)
  }

  const clearBets = () => {
    setInput("")
    setOutput("")
    setBetCount(0)
    setError("")
    setCopied(false)
  }

  return (
    <div className="bet-converter-shell" role="dialog" aria-modal="true" aria-label="Generate formatted bets">
      <div className="bet-converter-header">
        <div>
          <span className="bet-converter-kicker">BET FORMATTER</span>
          <h2>Generate formatted bets</h2>
        </div>
        <button type="button" className="bet-converter-close" onClick={onClose} aria-label="Close bet formatter">
          <svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true">
            <path d="M4 4L14 14M14 4L4 14" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
          </svg>
        </button>
      </div>

      <div className="bet-converter-body">
        <section className="bet-converter-step">
          <div className="bet-converter-step-head">
            <div className="bet-converter-step-title"><span>1</span><strong>Paste standard bets</strong></div>
            <button type="button" className="bet-converter-clear" onClick={clearBets} disabled={!input && !output}>
              Clear
            </button>
          </div>
          <p>Paste the original dash-separated result generated by the app.</p>
          <textarea
            className="bet-converter-textarea"
            value={input}
            onChange={(event) => { setInput(event.target.value); setOutput(""); setError("") }}
            placeholder="123-124-125-126..."
            spellCheck={false}
          />
        </section>

        <section className="bet-converter-step">
          <div className="bet-converter-step-head"><div className="bet-converter-step-title"><span>2</span><strong>Choose separator</strong></div></div>
          <div className="bet-converter-options" role="radiogroup" aria-label="Bet separator">
            {BET_COPY_FORMATS.map((item) => (
              <button
                type="button"
                role="radio"
                aria-checked={format === item.id}
                key={item.id}
                className={`bet-converter-option ${format === item.id ? "bet-converter-option--active" : ""}`}
                onClick={() => { setFormat(item.id); setOutput("") }}
              >
                <strong>{item.label}</strong><small>{item.preview}</small>
              </button>
            ))}
          </div>
        </section>

        <section className="bet-converter-step">
          <div className="bet-converter-step-head"><div className="bet-converter-step-title"><span>3</span><strong>Choose text style</strong></div></div>
          <div className="bet-converter-fonts" role="radiogroup" aria-label="Bet text style">
            {BET_COPY_TEXT_STYLES.map((item) => (
              <button
                type="button"
                role="radio"
                aria-checked={textStyle === item.id}
                key={item.id}
                className={`bet-converter-font bet-converter-font--${item.id} ${textStyle === item.id ? "bet-converter-option--active" : ""}`}
                onClick={() => { setTextStyle(item.id); setOutput("") }}
              >
                <span>123-456</span><small>{item.label}</small>
              </button>
            ))}
          </div>
        </section>

        <button type="button" className="bet-converter-generate" onClick={generate}>Generate formatted bets</button>
        {error && <div className="bet-converter-error" role="alert">{error}</div>}

        {output && (
          <section className="bet-converter-result">
            <div className="bet-converter-result-head">
              <div><strong>Formatted result</strong><span>{betCount} bets verified unchanged</span></div>
              <button type="button" onClick={copyOutput}>{copied ? "Copied!" : "Copy result"}</button>
            </div>
            <textarea className="bet-converter-textarea bet-converter-output" value={output} readOnly />
          </section>
        )}
      </div>
    </div>
  )
}
