"use client";

import { useEffect } from "react";

/**
 * Explicitly registers the service worker generated by next-pwa.
 *
 * We do this manually instead of relying on next-pwa's `register: true`
 * webpack plugin because the plugin-injected script does not reliably
 * execute inside Next.js App Router.  Doing it here gives us a guaranteed,
 * auditable registration call that happens on every page load.
 */
export default function PwaRegister() {
  useEffect(() => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;

    const register = () => {
      navigator.serviceWorker
        .register("/sw.js", { scope: "/", updateViaCache: "none" })
        .then(() => {
          window.dispatchEvent(new CustomEvent("pwa-service-worker-ready"));
        })
        .catch((err) => {
          console.warn("[PWA] Service worker registration failed:", err);
        });
    };

    // If the page is already loaded, register immediately.
    // Otherwise wait for the load event so we don't block first paint.
    if (document.readyState === "complete") {
      register();
    } else {
      window.addEventListener("load", register, { once: true });
    }
  }, []);

  return null;
}
